version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inventur_db
      MYSQL_USER: inventur_user
      MYSQL_PASSWORD: inventur_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://inventur_user:inventur_pass@db:3306/inventur_db
    volumes:
      - ./backend/app:/app/app
      - ./backend/.env:/app/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mysql_data:

